#cloud-config

# Cloudflare integration for Caddy servers
# Provides automatic IP range updates for trusted proxies and origin server protection
# Requires: base/caddy.yaml to be included first

write_files:
  # Systemd override for Caddy service
  - path: /etc/systemd/system/caddy.service.d/cloudflare.conf
    content: |
      [Service]
      EnvironmentFile=/etc/caddy/cloudflare.env
    permissions: '0644'
    owner: root:root

  - path: /usr/local/bin/update-cloudflare-ips-caddy.sh
    content: |
      #!/bin/bash
      
      # Script to update Cloudflare IPs via environment file
      
      # Configuration
      ENV_FILE="/etc/caddy/cloudflare.env"
      LOG_FILE="/var/log/cloudflare-update.log"
      
      # Function to log with timestamp
      log_message() {
          echo "$(date '+%Y-%m-%d %H:%M:%S'): $1" >> "$LOG_FILE"
      }
      
      # Fetch current Cloudflare IP ranges
      CLOUDFLARE_IPV4=$(curl -s -L https://www.cloudflare.com/ips-v4)
      CLOUDFLARE_IPV6=$(curl -s -L https://www.cloudflare.com/ips-v6)
      
      # Check if fetch was successful
      if [ -z "$CLOUDFLARE_IPV4" ] || [ -z "$CLOUDFLARE_IPV6" ]; then
          log_message "ERROR: Failed to fetch Cloudflare IP ranges"
          exit 1
      fi
      
      # Combine IPv4 and IPv6 ranges into a single space-separated string
      ALL_RANGES="$(printf "$CLOUDFLARE_IPV4" | sort --version-sort | tr '\n' ' ')$(echo "$CLOUDFLARE_IPV6" | sort --version-sort | tr '\n' ' ')"
      
      log_message "Found $(echo "$CLOUDFLARE_IPV4" | wc -l) IPv4 and $(echo "$CLOUDFLARE_IPV6" | wc -l) IPv6 ranges"
      
      # Update environment file
      cat > "$ENV_FILE" << EOF
      # Cloudflare IP ranges for trusted proxies and origin server protection
      # This file is automatically updated by /usr/local/bin/update-cloudflare-ips-caddy.sh
      # Last updated: $(date)
      CF_CIDRS=$ALL_RANGES
      EOF

      chmod 0644 "$ENV_FILE"

      # Reload Caddy to pick up new environment
      if systemctl reload caddy; then
          log_message "SUCCESS: Cloudflare IPs updated ($(echo "$CLOUDFLARE_IPV4" | wc -l) IPv4 + $(echo "$CLOUDFLARE_IPV6" | wc -l) IPv6) and Caddy reloaded"
      else
          log_message "ERROR: Failed to reload Caddy after IP update"
          exit 1
      fi
    permissions: '0755'
    owner: root:root

  # Daily cron script for Cloudflare IP updates
  - path: /etc/cron.daily/update-cloudflare-ips
    content: |
      #!/bin/bash
      # Daily update of Cloudflare IP ranges for Caddy
      /usr/local/bin/update-cloudflare-ips-caddy.sh
    permissions: '0755'
    owner: root:root

runcmd:
  - /usr/local/bin/update-cloudflare-ips-caddy.sh
  - systemctl daemon-reload